# Generated by Django 4.2.1 on 2023-06-11 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='travelapp_place',
        ),
    ]
